### ISSUE TITLE
tts报16388 'sign invalid'

### ISSUE THREAD

**Issue by afsxt** [w89612b/qqai-api-sdk#2]
speech.tts({
  text: "what's your name",
  speaker: 1,
}).then(res => {
  console.log(res);
});
报错： 16388 'sign invalid'
如果text: what is your name正常

**Comment by w89612b** [comment]
应该是编码的问题  我这两天修复一下

**Comment by w89612b** [comment]
npm 已经发布可更新

**Comment by afsxt** [comment]
可以了，谢了
